apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-service
  labels:
    app: document-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: document-service
  template:
    metadata:
      labels:
        app: document-service
    spec:
      containers:
        - name: document-service
          image: document-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /app/documentmanager-436319-7eda386e0f86.json
          volumeMounts:
            - name: gcp-credentials
              mountPath: /app
      volumes:
        - name: gcp-credentials
          secret:
            secretName: gcp-credentials-secret

---
apiVersion: v1
kind: Service
metadata:
  name: document-service
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
  selector:
    app: document-service
